allowBuilds:
  '@firebase/util': false
  esbuild: false
  protobufjs: false
ignoredBuiltDependencies:
  - '@firebase/util'
  - esbuild
  - protobufjs
minimumReleaseAgeExclude:
  - vite@8.1.2
audit:
  ignore:
    - GHSA-m9gg-hp2v-232j
    - GHSA-f596-whhp-79r4
